Ext.define( 'Ysn.model.baseproductModel', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'idx', type: 'int' },             
        { name: 'cate_lv1', type: 'string' },
        { name: 'cate_lv2', type: 'string' },
        { name: 'prod_code', type: 'string' },
        { name: 'prod_option1', type: 'string' },
        { name: 'prod_others', type: 'string' },    
        { name: 'eco_category', type: 'string' },
        { name: 'sample_modify', type: 'string' },
        { name: 'bottle_5K', type: 'float' },    
        { name: 'Innerbottle_5K', type: 'float' },
        { name: 'pumpcap_5K', type: 'float' },
        { name: 'cap_5K', type: 'float' },
        { name: 'tubesleeveheadering_5K', type: 'float' },
        { name: 'others_5K', type: 'float' },
        { name: 'set_5K', type: 'float' },
        { name: 'bottle_10K', type: 'float' },
        { name: 'Innerbottle_10K', type: 'float' },
        { name: 'pumpcap_10K', type: 'float' },
        { name: 'cap_10K', type: 'float' },
        { name: 'tubesleeveheadering_10K', type: 'float' },
        { name: 'others_10K', type: 'float' },
        { name: 'set_10K', type: 'float' },
        { name: 'bottle_30K', type: 'float' },
        { name: 'Innerbottle_30K', type: 'float' },
        { name: 'pumpcap_30K', type: 'float' },
        { name: 'cap_30K', type: 'float' },
        { name: 'tubesleeveheadering_30K', type: 'float' },
        { name: 'others_30K', type: 'float' },
        { name: 'set_30K', type: 'float' },
        { name: 'bottle_50K', type: 'float' },
        { name: 'Innerbottle_50K', type: 'float' },
        { name: 'pumpcap_50K', type: 'float' },
        { name: 'cap_50K', type: 'float' },
        { name: 'tubesleeveheadering_50K', type: 'float' },
        { name: 'others_50K', type: 'float' },
        { name: 'set_50K', type: 'float' },
        { name: 'bottle_100K', type: 'float' },
        { name: 'Innerbottle_100K', type: 'float' },
        { name: 'pumpcap_100K', type: 'float' },
        { name: 'cap_100K', type: 'float' },
        { name: 'tubesleeveheadering_100K', type: 'float' },
        { name: 'others_100K', type: 'float' },
        { name: 'set_100K', type: 'float' },
        { name: 'remark', type: 'string' },
        { name: 'create_id', type: 'string' },
        { name: 'create_date', type: 'date' },
        { name: 'modify_id', type: 'string' },
        { name: 'modify_date', type: 'date' },
        { name: 'del_yn', type: 'string' }
    ]
} );