Ext.define( 'Ysn.model.estimateitemModel', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'no', type: 'int' },
        { name: 'idx', type: 'int' },
        { name: 'estimate_id', type: 'string' },
        { name: 'sno', type: 'string' },
        { name: 'chk_print', type: 'string' },
        { name: 'summary_yn', type: 'string' },
        { name: 'set_yn', type: 'string' },
        { name: 'cate_lv1', type: 'string' },
        { name: 'cate_lv2', type: 'string' },
        { name: 'prod', type: 'string' },
        { name: 'sub_prod', type: 'string' },
        { name: 'prod_code', type: 'string' },
        { name: 'prod_option', type: 'string' },
        { name: 'prod_desc', type: 'string' },
        { name: 'eco_category', type: 'string' },
        { name: 'unit_price', type: 'float' },
        { name: 'quantity', type: 'int' },
        { name: 'amount', type: 'float' },
        { name: 'qty_5k', type: 'float' },
        { name: 'qty_10k', type: 'float' },
        { name: 'qty_30k', type: 'float' },
        { name: 'qty_50k', type: 'float' },
        { name: 'qty_100k', type: 'float' },
        { name: 'option_price', type: 'float' },
        { name: 'remark', type: 'string' },
        { name: 'create_id', type: 'string' },
        { name: 'create_date', type: 'date' },
        { name: 'modify_id', type: 'string' },
        { name: 'modify_date', type: 'date' },
        { name: 'del_yn', type: 'string' }
    ]
} );