Ext.define('Ysn.model.opportunityList', {   
            extend: 'Ext.data.Model', 
            fields: [  
                { name: 'OPPT_CD', type: 'string' },
				{ name: 'OPPT_TYPE', type: 'string' },
				{ name: 'OPPT_TYPE_NM', type: 'string'},
				{ name: 'ITEM_CD', type: 'string' },
				{ name: 'ITEM_NM', type: 'string' },
				{ name: 'ITEM_CD2', type: 'string' },
				{ name: 'BIZ_TYPE', type: 'string' },
				{ name: 'BIZ_TYPE_NM', type: 'string' },
				{ name: 'ITEM_TYPE_NM', type: 'string' },
				{ name: 'CUST_CD', type: 'string' },
				{ name: 'CUST_NM', type: 'string'},
				{ name: 'BAD_AR_YN', type: 'string' },
				{ name: 'USER_CD', type: 'string' },
				{ name: 'USER_NM', type: 'string' },
				{ name: 'DEPT_CD', type: 'string' },
				{ name: 'DEPT_NM', type: 'string' },
				{ name: 'EUSER_CD', type: 'string' },
				{ name: 'EUSER_NM', type: 'string' },
				{ name: 'DSTR_TYPE', type: 'string' },
				{ name: 'DSTR_TYPE_NM', type: 'string' },
				{ name: 'OPPT_STATUS', type: 'string' },
				{ name: 'OPPT_STATUS_NM', type: 'string' },
				{ name: 'WSO_PSBLT', type: 'string' },
				{ name: 'WSO_PSBLT_NM', type: 'string' },
				{ name: 'WSO_PSBLT_VALUE', type: 'string' },
				{ name: 'BASE_CRNY', type: 'string' },
				{ name: 'EXCH_RATE', type: 'string' },
				{ name: 'OPPT_QTY', type: 'string' },
				{ name: 'OPPT_UNIT_PRC', type: 'string' },
				{ name: 'AMOUNT', type: 'string' },
				{ name: 'KRW_AMOUNT', type: 'string' },
				{ name: 'PJT_CD', type: 'string' },
				{ name: 'PJT_NM', type: 'string' }, 
				{ name: 'WSO_PDATE', type: 'date', dateFormat: 'Ymd' }, 
				{ name: 'OPPT_SUMRY', type: 'string' },
                { name: 'RFC_CD', type: 'string' }
            ]  
});  

Ext.define('Ysn.model.forecastList', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'OPPT_CD', type: 'string' },
        { name: 'OPPT_TYPE', type: 'string' },
        { name: 'OPPT_TYPE_NM', type: 'string' },
        { name: 'ITEM_CD', type: 'string' },
        { name: 'ITEM_NM', type: 'string' },
        { name: 'ITEM_CD2', type: 'string' },
        { name: 'BIZ_TYPE', type: 'string' },
        { name: 'BIZ_TYPE_NM', type: 'string' },
        { name: 'ITEM_TYPE_NM', type: 'string' },
        { name: 'CUST_CD', type: 'string' },
        { name: 'CUST_NM', type: 'string' },
        { name: 'BAD_AR_YN', type: 'string' },
        { name: 'USER_CD', type: 'string' },
        { name: 'USER_NM', type: 'string' },
        { name: 'DEPT_CD', type: 'string' },
        { name: 'DEPT_NM', type: 'string' },
        { name: 'EUSER_CD', type: 'string' },
        { name: 'EUSER_NM', type: 'string' },
        { name: 'DSTR_TYPE', type: 'string' },
        { name: 'DSTR_TYPE_NM', type: 'string' },
        { name: 'OPPT_STATUS', type: 'string' },
        { name: 'OPPT_STATUS_NM', type: 'string' },
        { name: 'WSO_PSBLT', type: 'string' },
        { name: 'WSO_PSBLT_NM', type: 'string' },
        { name: 'WSO_PSBLT_VALUE', type: 'string' },
        { name: 'BASE_CRNY', type: 'string' },
        { name: 'EXCH_RATE', type: 'string' },
        { name: 'OPPT_QTY', type: 'string' },
        { name: 'OPPT_UNIT_PRC', type: 'string' },
        { name: 'AMOUNT', type: 'string' },
        { name: 'KRW_AMOUNT', type: 'string' },
        { name: 'PJT_CD', type: 'string' },
        { name: 'PJT_NM', type: 'string' },
        { name: 'WSO_PDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'OPPT_SUMRY', type: 'string' },
        { name: 'RFC_CD', type: 'string' },
        { name: 'CNFM_YN', type: 'string' },
        { name: 'BASE_YM', type: 'string' }
    ]
});

Ext.define('Ysn.model.opportunityDetail', {
    extend: 'Ext.data.Model',
    fields: [
        { mapping: 'OPPT_CD', name: 'oppt_cd', type: 'string' },
        { mapping: 'OPPT_TYPE', name: 'oppt_type', type: 'string' },
        { mapping: 'OPPT_TYPE_NM', name: 'oppt_type_nm', type: 'string' },
        { mapping: 'ITEM_CD', name: 'item_cd', type: 'string' },
        { mapping: 'ITEM_NM', name: 'item_nm', type: 'string' },
        { mapping: 'ITEM_CD2', name: 'item_cd2', type: 'string' },
        { mapping: 'BIZ_TYPE', name: 'biz_type', type: 'string' },
        { mapping: 'BIZ_TYPE_NM', name: 'biz_type_nm', type: 'string' },
        { mapping: 'ITEM_TYPE_NM', name: 'item_type_nm', type: 'string' },
        { mapping: 'CUST_CD', name: 'cust_cd', type: 'string' },
        { mapping: 'CUST_NM', name: 'cust_nm', type: 'string' },
        { mapping: 'BAD_AR_YN', name: 'bad_ar_yn', type: 'string' },
        { mapping: 'USER_CD', name: 'user_cd', type: 'string' },
        { mapping: 'USER_NM', name: 'user_nm', type: 'string' },
        { mapping: 'DEPT_CD', name: 'dept_cd', type: 'string' },
        { mapping: 'DEPT_NM', name: 'dept_nm', type: 'string' },
        { mapping: 'EUSER_CD', name: 'euser_cd', type: 'string' },
        { mapping: 'EUSER_NM', name: 'euser_nm', type: 'string' },
        { mapping: 'DSTR_TYPE', name: 'dstr_type', type: 'string' },
        { mapping: 'DSTR_TYPE_NM', name: 'dstr_type_nm', type: 'string' },
        { mapping: 'OPPT_STATUS', name: 'oppt_status', type: 'string' },
        { mapping: 'OPPT_STATUS_NM', name: 'oppt_status_nm', type: 'string' },
        { mapping: 'WSO_PSBLT', name: 'wso_psblt', type: 'string' },
        { mapping: 'WSO_PSBLT_NM', name: 'wso_psblt_nm', type: 'string' },
        { mapping: 'WSO_PSBLT_VALUE', name: 'wso_psblt_value', type: 'string' },
        { mapping: 'BASE_CRNY', name: 'base_crny', type: 'string' },
        { mapping: 'EXCH_RATE', name: 'exch_rate', type: 'string' },
        { mapping: 'OPPT_QTY', name: 'oppt_qty', type: 'string' },
        { mapping: 'OPPT_UNIT_PRC', name: 'oppt_unit_prc', type: 'string' },
        { mapping: 'AMOUNT', name: 'amount', type: 'string' },
        { mapping: 'KRW_AMOUNT', name: 'krw_amount', type: 'string' },
        { mapping: 'PJT_CD', name: 'pjt_cd', type: 'string' },
        { mapping: 'PJT_NM', name: 'pjt_nm', type: 'string' },
        { mapping: 'WSO_PDATE', name: 'wso_pdate', type: 'date', dateFormat: 'Ymd' },
        { mapping: 'OPPT_SUMRY', name: 'oppt_sumry', type: 'string' },
        { mapping: 'RFC_CD', name: 'rfc_cd', type: 'string' },
        { mapping: 'RFC_CHASU', name: 'rfc_chasu', type: 'string' }
    ]
});

Ext.define('Ysn.model.forecastDetail', {
    extend: 'Ext.data.Model',
    fields: [
        { mapping: 'OPPT_CD', name: 'oppt_cd', type: 'string' },
        { mapping: 'OPPT_TYPE', name: 'oppt_type', type: 'string' },
        { mapping: 'OPPT_TYPE_NM', name: 'oppt_type_nm', type: 'string' },
        { mapping: 'ITEM_CD', name: 'item_cd', type: 'string' },
        { mapping: 'ITEM_NM', name: 'item_nm', type: 'string' },
        { mapping: 'ITEM_CD2', name: 'item_cd2', type: 'string' },
        { mapping: 'BIZ_TYPE', name: 'biz_type', type: 'string' },
        { mapping: 'BIZ_TYPE_NM', name: 'biz_type_nm', type: 'string' },
        { mapping: 'ITEM_TYPE_NM', name: 'item_type_nm', type: 'string' },
        { mapping: 'CUST_CD', name: 'cust_cd', type: 'string' },
        { mapping: 'CUST_NM', name: 'cust_nm', type: 'string' },
        { mapping: 'BAD_AR_YN', name: 'bad_ar_yn', type: 'string' },
        { mapping: 'USER_CD', name: 'user_cd', type: 'string' },
        { mapping: 'USER_NM', name: 'user_nm', type: 'string' },
        { mapping: 'DEPT_CD', name: 'dept_cd', type: 'string' },
        { mapping: 'DEPT_NM', name: 'dept_nm', type: 'string' },
        { mapping: 'EUSER_CD', name: 'euser_cd', type: 'string' },
        { mapping: 'EUSER_NM', name: 'euser_nm', type: 'string' },
        { mapping: 'DSTR_TYPE', name: 'dstr_type', type: 'string' },
        { mapping: 'DSTR_TYPE_NM', name: 'dstr_type_nm', type: 'string' },
        { mapping: 'OPPT_STATUS', name: 'oppt_status', type: 'string' },
        { mapping: 'OPPT_STATUS_NM', name: 'oppt_status_nm', type: 'string' },
        { mapping: 'WSO_PSBLT', name: 'wso_psblt', type: 'string' },
        { mapping: 'WSO_PSBLT_NM', name: 'wso_psblt_nm', type: 'string' },
        { mapping: 'WSO_PSBLT_VALUE', name: 'wso_psblt_value', type: 'string' },
        { mapping: 'BASE_CRNY', name: 'base_crny', type: 'string' },
        { mapping: 'EXCH_RATE', name: 'exch_rate', type: 'string' },
        { mapping: 'OPPT_QTY', name: 'oppt_qty', type: 'string' },
        { mapping: 'OPPT_UNIT_PRC', name: 'oppt_unit_prc', type: 'string' },
        { mapping: 'AMOUNT', name: 'amount', type: 'string' },
        { mapping: 'KRW_AMOUNT', name: 'krw_amount', type: 'string' },
        { mapping: 'PJT_CD', name: 'pjt_cd', type: 'string' },
        { mapping: 'PJT_NM', name: 'pjt_nm', type: 'string' },
        { mapping: 'WSO_PDATE', name: 'wso_pdate', type: 'date', dateFormat: 'Ymd' },
        { mapping: 'OPPT_SUMRY', name: 'oppt_sumry', type: 'string' },
        { mapping: 'RFC_CD', name: 'rfc_cd', type: 'string' },
        { mapping: 'RFC_CHASU', name: 'rfc_chasu', type: 'string' },
        { mapping: 'CNFM_YN', name: 'cnfm_yn', type: 'string' },
        { mapping: 'CHKBASEYN', name: 'chkbaseyn', type: 'string' },
        { mapping: 'BASE_YM', name: 'base_ym', type: 'string' }
    ]
});

Ext.define('Ysn.model.opportunityItem', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'IDX', type: 'string' },
        { name: 'ITEM_CD2', type: 'string' }, 
        { name: 'ITEM_NM', type: 'string' }, 
        { name: 'BASE_CRNY', type: 'string' },
        { name: 'EXCH_RATE', type: 'string' },
        { name: 'OPPT_QTY', type: 'string' },
        { name: 'OPPT_UNIT_PRC', type: 'string' },
        { name: 'AMOUNT', type: 'string' },
        { name: 'KRW_AMOUNT', type: 'string' }, 
        { name: 'SALES_DATE', type: 'date', dateFormat: 'Ymd' }
    ]
});

Ext.define('Ysn.model.forecastItem', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'IDX', type: 'string' },
        { name: 'ITEM_CD2', type: 'string' },
        { name: 'ITEM_NM', type: 'string' },
        { name: 'BASE_CRNY', type: 'string' },
        { name: 'EXCH_RATE', type: 'string' },
        { name: 'OPPT_QTY', type: 'string' },
        { name: 'OPPT_UNIT_PRC', type: 'string' },
        { name: 'AMOUNT', type: 'string' },
        { name: 'KRW_AMOUNT', type: 'string' },
        { name: 'SALES_DATE', type: 'date', dateFormat: 'Ymd' }
    ]
});

Ext.define('Ysn.model.salesOrderList', {
    extend: 'Ext.data.Model',
    fields: [
       { name: 'SO_CD', type: 'string' },
        { name: 'SO_SEQ', type: 'string' },
        { name: 'SO_SERL', type: 'string' },
        { name: 'ORD_CDATE', type: 'date', dateFormat: 'Ymd'},
        { name: 'LOT_NO', type: 'string' },
        { name: 'ITEM_CD', type: 'string' },
        { name: 'ITEM_CD2', type: 'string' },
        { name: 'ITEM_NM', type: 'string' },
        { name: 'CUST_NM', type: 'string' },
        { name: 'EUSER_CD', type: 'string' },
        { name: 'EUSER_NM', type: 'string' },
        { name: 'DEPT_CD', type: 'string' },
        { name: 'DEPT_NM', type: 'string' },
        { name: 'USER_CD', type: 'string' },
        { name: 'USER_NM', type: 'string' },
        { name: 'ITEM_LEVEL1', type: 'string' },
        { name: 'ITEM_LEVEL2', type: 'string' },
        { name: 'ITEM_LEVEL3', type: 'string' },
        { name: 'DSTR_TYPE', type: 'string' },
        { name: 'DSTR_TYPE_NM', type: 'string' },
        { name: 'BIZ_TYPE', type: 'string' },
        { name: 'BIZ_TYPE_NM', type: 'string' },
        { name: 'ITEM_TYPE', type: 'string' },
        { name: 'ITEM_TYPE_NM', type: 'string' },
        { name: 'SALES_PDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'SALES_DDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'SALES_ODATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'SO_STATUS', type: 'string' },
        { name: 'SO_STATUS_NM', type: 'string' },
        { name: 'BASE_CRNY', type: 'string' },
        { name: 'EXCH_RATE', type: 'string' },
        { name: 'QTY', type: 'int' },
        { name: 'CUST_SP_QTY', type: 'int' },
        { name: 'UNIT_PRICE', type: 'string' },
        { name: 'AMOUNT', type: 'float' },
        { name: 'KRW_AMOUNT', type: 'int' },
        { name: 'SALES_WDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'WSO_QTY', type: 'int' },
        { name: 'WSO_AMOUNT', type: 'float' },
        { name: 'WSO_KRW_AMOUNT', type: 'int' },
        { name: 'OWH_QTY', type: 'int' },
        { name: 'OWH_AMOUNT', type: 'float' },
        { name: 'OWH_KRW_AMOUNT', type: 'int' },
        { name: 'PO_CD', type: 'string' },
        { name: 'ORD_GB_L', type: 'string' },
        { name: 'ORD_GB_L_NM', type: 'string' },
        { name: 'ORD_GB_M', type: 'string' },
        { name: 'ORD_GB_M_NM', type: 'string' },
        { name: 'ORD_GB_S', type: 'string' },
        { name: 'ORD_GB_S_NM', type: 'string' },
        { name: 'CTLG_CD', type: 'string' },
        { name: 'PJT_CD', type: 'string' },
        { name: 'PJT_NM', type: 'string' },
        { name: 'CLOSE_YN', type: 'string' },
        { name: 'REMARK', type: 'string' },
        { name: 'DUMMY8', type: 'string' },
        { name: 'JNB_DEPT_NM', type: 'string' } 
    ]
});

Ext.define('Ysn.model.salesOrderDetail', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'so_cd', mapping: 'SO_CD', type: 'string' },
        { name: 'so_seq', mapping: 'SO_SEQ', type: 'string' },
        { name: 'so_serl', mapping: 'SO_SERL', type: 'string' },
        { name: 'ord_cdate', mapping: 'ORD_CDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'lot_no', mapping: 'LOT_NO', type: 'string' },
        { name: 'item_cd', mapping: 'ITEM_CD', type: 'string' },
        { name: 'item_cd2', mapping: 'ITEM_CD2', type: 'string' },
        { name: 'item_nm', mapping: 'ITEM_NM', type: 'string' },
        { name: 'cust_nm', mapping: 'CUST_NM', type: 'string' },
        { name: 'euser_cd', mapping: 'EUSER_CD', type: 'string' },
        { name: 'euser_nm', mapping: 'EUSER_NM', type: 'string' },
        { name: 'dept_cd', mapping: 'DEPT_CD', type: 'string' },
        { name: 'dept_nm', mapping: 'DEPT_NM', type: 'string' },
        { name: 'user_cd', mapping: 'USER_CD', type: 'string' },
        { name: 'user_nm', mapping: 'USER_NM', type: 'string' },
        { name: 'item_level1', mapping: 'ITEM_LEVEL1', type: 'string' },
        { name: 'item_level2', mapping: 'ITEM_LEVEL2', type: 'string' },
        { name: 'item_level3', mapping: 'ITEM_LEVEL3', type: 'string' },
        { name: 'dstr_type', mapping: 'DSTR_TYPE', type: 'string' },
        { name: 'dstr_type_nm', mapping: 'DSTR_TYPE_NM', type: 'string' },
        { name: 'biz_type', mapping: 'BIZ_TYPE', type: 'string' },
        { name: 'biz_type_nm', mapping: 'BIZ_TYPE_NM', type: 'string' },
        { name: 'item_type', mapping: 'ITEM_TYPE', type: 'string' },
        { name: 'item_type_nm', mapping: 'ITEM_TYPE_NM', type: 'string' },
        { name: 'sales_pdate', mapping: 'SALES_PDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'sales_ddate', mapping: 'SALES_DDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'sales_odate', mapping: 'SALES_ODATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'so_status', mapping: 'SO_STATUS', type: 'string' },
        { name: 'so_status_nm', mapping: 'SO_STATUS_NM', type: 'string' },
        { name: 'base_crny', mapping: 'BASE_CRNY', type: 'string' },
        { name: 'exch_rate', mapping: 'EXCH_RATE', type: 'string' },
        { name: 'qty', mapping: 'QTY', type: 'string' },
        { name: 'cust_sp_qty', mapping: 'CUST_SP_QTY', type: 'string' },
        { name: 'unit_price', mapping: 'UNIT_PRICE', type: 'string' },
        { name: 'amount', mapping: 'AMOUNT', type: 'string' },
        { name: 'krw_amount', mapping: 'KRW_AMOUNT', type: 'string' },
        { name: 'sales_wdate', mapping: 'SALES_WDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'wso_qty', mapping: 'WSO_QTY', type: 'string' },
        { name: 'wso_amount', mapping: 'WSO_AMOUNT', type: 'string' },
        { name: 'wso_krw_amount', mapping: 'WSO_KRW_AMOUNT', type: 'string' },
        { name: 'owh_qty', mapping: 'OWH_QTY', type: 'string' },
        { name: 'owh_amount', mapping: 'OWH_AMOUNT', type: 'string' },
        { name: 'owh_krw_amount', mapping: 'OWH_KRW_AMOUNT', type: 'string' },
        { name: 'po_cd', mapping: 'PO_CD', type: 'string' },
        { name: 'ord_gb_l', mapping: 'ORD_GB_L', type: 'string' },
        { name: 'ord_gb_l_nm', mapping: 'ORD_GB_L_NM', type: 'string' },
        { name: 'ord_gb_m', mapping: 'ORD_GB_M', type: 'string' },
        { name: 'ord_gb_m_nm', mapping: 'ORD_GB_M_NM', type: 'string' },
        { name: 'ord_gb_s', mapping: 'ORD_GB_S', type: 'string' },
        { name: 'ord_gb_s_nm', mapping: 'ORD_GB_S_NM', type: 'string' },
        { name: 'ctlg_cd', mapping: 'CTLG_CD', type: 'string' },
        { name: 'pjt_cd', mapping: 'PJT_CD', type: 'string' },
        { name: 'pjt_nm', mapping: 'PJT_NM', type: 'string' },
        { name: 'close_yn', mapping: 'CLOSE_YN', type: 'string' },
        { name: 'remark', mapping: 'REMARK', type: 'string' },
        { name: 'dummy8', mapping: 'DUMMY8', type: 'string' },
        { name: 'jnb_dept_nm', mapping: 'JNB_DEPT_NM', type: 'string' }
    ]
});

Ext.define('Ysn.model.salesOrderItem1', {
    extend: 'Ext.data.Model',
    fields: [ 
        { name: 'ITEM_CD2', type: 'string' },
        { name: 'ITEM_NM', type: 'string' },
        { name: 'BASE_CRNY', type: 'string' },
        { name: 'EXCH_RATE', type: 'string' },
        { name: 'QTY', type: 'string' },
        { name: 'UNIT_PRICE', type: 'string' },
        { name: 'AMOUNT', type: 'string' },
        { name: 'KRW_AMOUNT', type: 'string' },
        { name: 'SALES_PDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'SALES_DDATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'SO_CD', type: 'string' },
        { name: 'SO_SEQ', type: 'string' },
        { name: 'SO_SERL', type: 'string' },
        { name: 'ITEM_CD', type: 'string' },
        { name: 'LOT_NO', type: 'string' } 
    ]
});

Ext.define('Ysn.model.salesOrderItem2', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'ITEM_CD2', type: 'string' },
        { name: 'ITEM_NM', type: 'string' },
        { name: 'BASE_CRNY', type: 'string' },
        { name: 'EXCH_RATE', type: 'string' },
        { name: 'OWH_QTY', type: 'string' },
        { name: 'OWH_UNIT_PRICE', type: 'string' },
        { name: 'OWH_AMOUNT', type: 'string' },
        { name: 'OWH_KRW_AMOUNT', type: 'string' },
        { name: 'SALES_ODATE', type: 'date', dateFormat: 'Ymd' },
        { name: 'SO_CD', type: 'string' },
        { name: 'SO_SEQ', type: 'string' },
        { name: 'SO_SERL', type: 'string' },
        { name: 'ITEM_CD', type: 'string' },
        { name: 'LOT_NO', type: 'string' }
    ]
});

Ext.define('Ysn.model.salesOrderItem3', {
    extend: 'Ext.data.Model',
    fields: [ 
        { name: 'ITEM_CD2', type: 'string' },
        { name: 'ITEM_NM', type: 'string' },
        { name: 'BASE_CRNY', type: 'string' },
        { name: 'EXCH_RATE', type: 'string' },
        { name: 'BILL_QTY', type: 'string' },
        { name: 'BILL_UNIT_PRICE', type: 'string' },
        { name: 'BILL_AMOUNT', type: 'string' },
        { name: 'BILL_KRW_AMOUNT', type: 'string' },
        { name: 'SALES_BDATE', type: 'date', dateFormat: 'Ymd' }, 
        { name: 'ITEM_CD', type: 'string' } 
    ]
});



