Ext.define('Ysn.model.orderTargetSalesList', {   
            extend: 'Ext.data.Model', 
            fields: [  
                { name: 'UP_DEPT_CD', type: 'string' },
				{ name: 'UP_DEPT_NM', type: 'string' },
				{ name: 'DEPT_CD', type: 'string'},
				{ name: 'DEPT_NM', type: 'string' },
				{ name: 'USER_CD', type: 'string' },
				{ name: 'USER_NM', type: 'string' },
				{ name: 'DSTR_TYPE', type: 'string' },
                { name: 'DSTR_TYPE_NM', type: 'string' }, 
                { name: 'BIZ_TYPE', type: 'string' },
                { name: 'BIZ_TYPE_NM', type: 'string' },
				{ name: 'ITEM_TYPE', type: 'string' },
				{ name: 'ITEM_TYPE_NM', type: 'string' },
				{ name: 'CUST_CD', type: 'string' },
				{ name: 'CUST_NM', type: 'string'},
				{ name: 'EUSER_CD', type: 'string' },
				{ name: 'EUSER_NM', type: 'string' },
				{ name: 'AMOUNT1', type: 'string' },
				{ name: 'AMOUNT2', type: 'string' },
				{ name: 'AMOUNT3', type: 'string' },
				{ name: 'AMOUNT4', type: 'string' },
				{ name: 'ARCHIVE_RATE5', type: 'string' },
				{ name: 'AMOUNT6', type: 'string' },
				{ name: 'ELONG_RATE7', type: 'string' },
				{ name: 'AMOUNT11', type: 'string' },
				{ name: 'AMOUNT12', type: 'string' },
				{ name: 'AMOUNT13', type: 'string' },
				{ name: 'AMOUNT14', type: 'string' },
				{ name: 'ARCHIVE_RATE15', type: 'string' },
				{ name: 'AMOUNT16', type: 'string' },
				{ name: 'MM1', type: 'string' }, 
				{ name: 'MM2', type: 'string' }, 
				{ name: 'MM3', type: 'string' }, 
				{ name: 'MM4', type: 'string' }, 
				{ name: 'MM5', type: 'string' }, 
				{ name: 'MM6', type: 'string' }, 
				{ name: 'MM7', type: 'string' }, 
				{ name: 'MM8', type: 'string' }, 
				{ name: 'MM9', type: 'string' }, 
				{ name: 'MM10', type: 'string' }, 
				{ name: 'MM11', type: 'string' }, 
				{ name: 'MM12', type: 'string' }
            ]  
});

Ext.define('Ysn.model.selectOrderResult', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'UP_DEPT_CD', type: 'string' },
        { name: 'UP_DEPT_NM', type: 'string' },
        { name: 'DEPT_CD', type: 'string' },
        { name: 'DEPT_NM', type: 'string' },
        { name: 'USER_CD', type: 'string' },
        { name: 'USER_NM', type: 'string' },
        { name: 'DSTR_TYPE', type: 'string' },
        { name: 'DSTR_TYPE_NM', type: 'string' },
        { name: 'BIZ_TYPE', type: 'string' },
        { name: 'BIZ_TYPE_NM', type: 'string' },
        { name: 'ITEM_TYPE', type: 'string' },
        { name: 'ITEM_TYPE_NM', type: 'string' },
        { name: 'CUST_CD', type: 'string' },
        { name: 'CUST_NM', type: 'string' },
        { name: 'EUSER_CD', type: 'string' },
        { name: 'EUSER_NM', type: 'string' },
        { name: 'AMOUNT1', type: 'string' },
        { name: 'AMOUNT2', type: 'string' },
        { name: 'AMOUNT3', type: 'string' },
        { name: 'RATE4', type: 'string' },
		{ name: 'MM1', type: 'string' },
		{ name: 'MM2', type: 'string' },
		{ name: 'MM3', type: 'string' },
		{ name: 'MM4', type: 'string' },
		{ name: 'MM5', type: 'string' },
		{ name: 'MM6', type: 'string' },
		{ name: 'MM7', type: 'string' },
		{ name: 'MM8', type: 'string' },
		{ name: 'MM9', type: 'string' },
		{ name: 'MM10', type: 'string' },
		{ name: 'MM11', type: 'string' },
		{ name: 'MM12', type: 'string' }
    ]
});

Ext.define('Ysn.model.selectDivOrderResult', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'UP_DEPT_CD', type: 'string' },
        { name: 'UP_DEPT_NM', type: 'string' },
        { name: 'DEPT_CD', type: 'string' },
        { name: 'DEPT_NM', type: 'string' },
        { name: 'USER_CD', type: 'string' },
        { name: 'USER_NM', type: 'string' },
        { name: 'DSTR_TYPE', type: 'string' },
        { name: 'DSTR_TYPE_NM', type: 'string' },
        { name: 'BIZ_TYPE', type: 'string' },
        { name: 'BIZ_TYPE_NM', type: 'string' },
        { name: 'ITEM_TYPE', type: 'string' },
        { name: 'ITEM_TYPE_NM', type: 'string' },
        { name: 'CUST_CD', type: 'string' },
        { name: 'CUST_NM', type: 'string' },
        { name: 'EUSER_CD', type: 'string' },
        { name: 'EUSER_NM', type: 'string' },
        { name: 'AMOUNT1', type: 'string' },
        { name: 'AMOUNT2', type: 'string' },
        { name: 'AMOUNT3', type: 'string' },
        { name: 'RATE4', type: 'string' },
        { name: 'MM1', type: 'string' },
        { name: 'MM2', type: 'string' },
        { name: 'MM3', type: 'string' },
        { name: 'MM4', type: 'string' }
    ]
});

Ext.define('Ysn.model.salesTargetSalesList', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'UP_DEPT_CD', type: 'string' },
        { name: 'UP_DEPT_NM', type: 'string' },
        { name: 'DEPT_CD', type: 'string' },
        { name: 'DEPT_NM', type: 'string' },
        { name: 'USER_CD', type: 'string' },
        { name: 'USER_NM', type: 'string' },
        { name: 'DSTR_TYPE', type: 'string' },
        { name: 'DSTR_TYPE_NM', type: 'string' },
        { name: 'BIZ_TYPE', type: 'string' },
        { name: 'BIZ_TYPE_NM', type: 'string' },
        { name: 'ITEM_TYPE', type: 'string' },
        { name: 'ITEM_TYPE_NM', type: 'string' },
        { name: 'CUST_CD', type: 'string' },
        { name: 'CUST_NM', type: 'string' },
        { name: 'EUSER_CD', type: 'string' },
        { name: 'EUSER_NM', type: 'string' },
        { name: 'AMOUNT1', type: 'string' },
        { name: 'AMOUNT2', type: 'string' },
        { name: 'AMOUNT3', type: 'string' },
        { name: 'AMOUNT4', type: 'string' },
        { name: 'ARCHIVE_RATE5', type: 'string' },
        { name: 'AMOUNT6', type: 'string' },
        { name: 'ELONG_RATE7', type: 'string' },
        { name: 'AMOUNT11', type: 'string' },
        { name: 'AMOUNT12', type: 'string' },
        { name: 'AMOUNT13', type: 'string' },
        { name: 'AMOUNT14', type: 'string' },
        { name: 'ARCHIVE_RATE15', type: 'string' },
        { name: 'AMOUNT16', type: 'string' },
        { name: 'MM1', type: 'string' },
        { name: 'MM2', type: 'string' },
        { name: 'MM3', type: 'string' },
        { name: 'MM4', type: 'string' },
        { name: 'MM5', type: 'string' },
        { name: 'MM6', type: 'string' },
        { name: 'MM7', type: 'string' },
        { name: 'MM8', type: 'string' },
        { name: 'MM9', type: 'string' },
        { name: 'MM10', type: 'string' },
        { name: 'MM11', type: 'string' },
        { name: 'MM12', type: 'string' }
    ]
});

Ext.define('Ysn.model.selectSalesResult', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'UP_DEPT_CD', type: 'string' },
        { name: 'UP_DEPT_NM', type: 'string' },
        { name: 'DEPT_CD', type: 'string' },
        { name: 'DEPT_NM', type: 'string' },
        { name: 'USER_CD', type: 'string' },
        { name: 'USER_NM', type: 'string' },
        { name: 'DSTR_TYPE', type: 'string' },
        { name: 'DSTR_TYPE_NM', type: 'string' },
        { name: 'BIZ_TYPE', type: 'string' },
        { name: 'BIZ_TYPE_NM', type: 'string' },
        { name: 'ITEM_TYPE', type: 'string' },
        { name: 'ITEM_TYPE_NM', type: 'string' },
        { name: 'CUST_CD', type: 'string' },
        { name: 'CUST_NM', type: 'string' },
        { name: 'EUSER_CD', type: 'string' },
        { name: 'EUSER_NM', type: 'string' },
        { name: 'AMOUNT1', type: 'string' },
        { name: 'AMOUNT2', type: 'string' },
        { name: 'AMOUNT3', type: 'string' },
        { name: 'RATE4', type: 'string' },
		{ name: 'MM1', type: 'string' },
		{ name: 'MM2', type: 'string' },
		{ name: 'MM3', type: 'string' },
		{ name: 'MM4', type: 'string' },
		{ name: 'MM5', type: 'string' },
		{ name: 'MM6', type: 'string' },
		{ name: 'MM7', type: 'string' },
		{ name: 'MM8', type: 'string' },
		{ name: 'MM9', type: 'string' },
		{ name: 'MM10', type: 'string' },
		{ name: 'MM11', type: 'string' },
		{ name: 'MM12', type: 'string' }
    ]
});

Ext.define('Ysn.model.selectDivSalesResult', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'UP_DEPT_CD', type: 'string' },
        { name: 'UP_DEPT_NM', type: 'string' },
        { name: 'DEPT_CD', type: 'string' },
        { name: 'DEPT_NM', type: 'string' },
        { name: 'USER_CD', type: 'string' },
        { name: 'USER_NM', type: 'string' },
        { name: 'DSTR_TYPE', type: 'string' },
        { name: 'DSTR_TYPE_NM', type: 'string' },
        { name: 'BIZ_TYPE', type: 'string' },
        { name: 'BIZ_TYPE_NM', type: 'string' },
        { name: 'ITEM_TYPE', type: 'string' },
        { name: 'ITEM_TYPE_NM', type: 'string' },
        { name: 'CUST_CD', type: 'string' },
        { name: 'CUST_NM', type: 'string' },
        { name: 'EUSER_CD', type: 'string' },
        { name: 'EUSER_NM', type: 'string' },
        { name: 'AMOUNT1', type: 'string' },
        { name: 'AMOUNT2', type: 'string' },
        { name: 'AMOUNT3', type: 'string' },
        { name: 'RATE4', type: 'string' },
        { name: 'MM1', type: 'string' },
        { name: 'MM2', type: 'string' },
        { name: 'MM3', type: 'string' },
        { name: 'MM4', type: 'string' }
    ]
});

Ext.define('Ysn.model.deferredBoundsList', {
    extend: 'Ext.data.Model',
    fields: [ 
        { name: 'UP_DEPT_NM', type: 'string' }, 
        { name: 'DEPT_NM', type: 'string' }, 
        { name: 'USER_NM', type: 'string' }, 
        { name: 'CUST_NM', type: 'string' }, 
        { name: 'AMOUNT_1', type: 'string' },
        { name: 'AMOUNT_2', type: 'string' },
        { name: 'AMOUNT_3', type: 'string' },
        { name: 'AMOUNT_4', type: 'string' },
        { name: 'AMOUNT_5', type: 'string' },
        { name: 'AMOUNT_6', type: 'string' },
        { name: 'AMOUNT_7', type: 'string' },
        { name: 'AMOUNT_8', type: 'string' },
        { name: 'BAD_AR_YN', type: 'string' },
        { name: 'TRMS_PAY_NM', type: 'string' } 
    ]
});





