Ext.define('Ysn.model.sampleRequestList', {   //TRACKING_NUM
            extend: 'Ext.data.Model', 
            fields: [  
                {name: 'COMPANY_CD', type: 'string'},
				{name: 'SMR_CD', type: 'string'},
				{ name: 'SMR_CHASU', type: 'string' },
                { name: 'TRACKING_NUM', type: 'string' },
                { name: 'PROCESS_NM', type: 'string' },
                { name: 'DELAY_COMMENT_NM', type: 'string' }, 
				{name: 'ITEM_CD', type: 'string'},
				{name: 'ITEM_NM', type: 'string'},
				{name: 'EUSER_CD', type: 'string'},
				{name: 'EUSER_NM', type: 'string'},
				{name: 'QRUSER_CD', type: 'string'},
				{name: 'QRUSER_NM', type: 'string'},
				{name: 'QDEPT_CD', type: 'string'},
				{name: 'QDEPT_NM', type: 'string'},
				{name: 'RRUSER_CD', type: 'string'},
				{name: 'RRUSER_NM', type: 'string'},
				{name: 'RAUSER', type: 'string'},
				{name: 'RAUSER_NM', type: 'string'},
				{name: 'SMP_STATUS', type: 'string'},
				{ name: 'SMP_STATUS_NM', type: 'string' },
				{ name: 'PRDT_PDATE2', type: 'date', dateFormat: 'Ymd' },
				{name: 'SMR_RQDATE', type: 'date', dateFormat:'Ymd'},
				{name: 'SMR_BKDATE', type: 'date', dateFormat:'Ymd'},
				{name: 'SMR_RRDATE', type: 'date', dateFormat:'Ymd'},
				{name: 'SMR_FBDATE', type: 'date', dateFormat:'Ymd'},
				{name: 'SMR_PRDATE', type: 'date', dateFormat:'Ymd'},
				{name: 'PRDT_PDATE', type: 'date', dateFormat:'Ymd'},
				{name: 'SHIP_PDATE', type: 'date', dateFormat:'Ymd'},
				{name: 'SMR_RADATE', type: 'date', dateFormat:'Ymd'},
				{name: 'SMR_PODATE', type: 'date', dateFormat:'Ymd'},
				{name: 'SMR_ORDERDATE', type: 'date', dateFormat:'Ymd'},
				{name: 'SHIP_PDATE', type: 'date', dateFormat:'Ymd'}, 
				{ name: 'PROJECT_POSS', type: 'string' },
                { name: 'SMP_RQTY', type: 'string' },
                { name: 'PUR_OQTY', type: 'string' }
            ]  
});  

Ext.define('Ysn.model.sampleRequestDetail', {   
            extend: 'Ext.data.Model', 
            fields: [ 'BOTTLE_PART_LIST','BOTTLE_PKG','BOTTLE_REMARK_CMT','OVERCAP_PART_LIST',
				'OVERCAP_PKG','OVERCAP_REMARK_CMT','PRD_INFO','PUMP_PART_LIST','PUMP_PKG','PUMP_REMARK_CMT','REQ_DETAIL']  
});  


Ext.define('Ysn.model.sampleProductionList', {   
            extend: 'Ext.data.Model', 
            fields: [  
			    {name:'SMP_CD',	type: 'string'},			
				{name:'SMP_CHASU', type: 'string'},	
				{name:'SMR_CD',	type: 'string'},			
				{name:'SMR_CHASU', type: 'string'},	
				{name:'ITEM_NM', type: 'string'},	
				{name:'ITEM_CD', type: 'string'},		
				{name:'CUST_NM', type: 'string'},	
				{name:'CUST_CD', type: 'string'},			
				{name:'EUSER_NM', type: 'string'},	
				{name:'EUSER_CD', type: 'string'},	
				{name:'DSTR_TYPE', type: 'string'},	
				{name:'DSTR_TYPE_NM', type: 'string'},	
				{name:'DEPT_NM', type: 'string'},	
				{name:'DEPT_CD', type: 'string'},	
				{name:'USER_NM', type: 'string'},	
				{name:'USER_CD', type: 'string'},		
				{name:'MUSER_NM'},	
				{name:'MUSER_CD', type: 'string'},	
				{name:'BIZ_TYPE', type: 'string'},	
				{name:'BIZ_TYPE_NM', type: 'string'},	
				{ name: 'SMP_STATUS', type: 'string' },
                { name: 'SMP_RQTY', type: 'string' },
				{ name: 'SMP_RQTY2', type: 'string' },
				{name:'SMP_STATUS_NM', type: 'string'},
				{name:'PRDT_PSBLT', type: 'string'},	
				{name:'PRDT_PSBLT_NM', type: 'string'},		
				{name:'SMP_RDATE', type: 'date', dateFormat:'Ymd'},
				{name:'PRDT_RCDATE', type: 'date', dateFormat:'Ymd'},
				{ name: 'FILM_FDATE', type: 'date', dateFormat: 'Ymd' },
				{ name: 'FILM_CDATE', type: 'date', dateFormat: 'Ymd' },
				{ name: 'TARGET_FDATE', type: 'date', dateFormat: 'Ymd' },
				{name:'CMPT_RDATE', type: 'date', dateFormat:'Ymd'},
				{ name: 'PRDT_RDATE', type: 'date', dateFormat: 'Ymd' },
                { name: 'PRDT_ADATE', type: 'date', dateFormat: 'Ymd' },
                { name: 'PRDT_PDATE', type: 'date', dateFormat: 'Ymd' },
                { name: 'PRDT_PDATE2', type: 'date', dateFormat: 'Ymd' }, 
				{ name: 'DELAY_COMMENT', type: 'string' },
                { name: 'PROCESS', type: 'string' },
                { name: 'DELAY_COMMENT_NM', type: 'string' },
                { name: 'PROCESS_NM', type: 'string' },
				{name:'FILM_RDATE', type: 'date', dateFormat:'Ymd'},
				{name:'PRDT_CDATE', type: 'date', dateFormat:'Ymd'},
				{name:'SHIP_PDATE', type: 'date', dateFormat:'Ymd'},
				{ name: 'ITEM_TYPE', type: 'string' },
				{name:'ITEM_TYPE_NM', type: 'string'},	
				{ name: 'PJT_NM', type: 'string' },
                { name: 'SMP_TYPE', type: 'string' },
                { name: 'SMP_TYPE_NM', type: 'string' },
				{ name: 'BAD_AR_YN', type: 'string' },
                { name: 'NONFREE_YN', type: 'string' },
                { name: 'SMP_CRTYPE_NM', type: 'string' }, 
                { name: 'PUR_OQTY', type: 'string' }
                
            ]  
}); 
			
Ext.define('Ysn.model.sampleProductionDetail', {   
            extend: 'Ext.data.Model', 
            fields: [  
			    {mapping:'SMP_CD', name:'smp_cd',	type: 'string'},			
				{mapping:'SMP_CHASU',name:'smp_chasu',	type: 'string'},
				{mapping:'SMR_CD',	name: 'smr_cd', type: 'string'},			
				{mapping:'SMR_CHASU', name: 'smr_chasu', type: 'string'},		
				{mapping:'ITEM_NM',	name:'item_nm',	type: 'string'},	
				{mapping:'ITEM_CD',name:'item_cd',		type: 'string'},	
				{mapping:'PJT_CD',name:'pjt_cd',	type: 'string'},	
				{mapping:'PJT_NM',name:'pjt_nm',	type: 'string'},				
				{mapping:'CUST_NM',name:'cust_nm', type: 'string'},	
				{mapping:'CUST_CD',name:'cust_cd', type: 'string'},			
				{mapping:'EUSER_NM',name:'euser_nm', type: 'string'},	
				{mapping:'EUSER_CD',name:'euser_cd', type: 'string'},	
				{mapping:'BIZ_TYPE',name:'biz_type', type: 'string'},	
				{mapping:'BIZ_TYPE_NM',name:'biz_type_nm', type: 'string'},	
				{mapping:'DSTR_TYPE',name:'dstr_type', type: 'string'},	
				{mapping:'DSTR_TYPE_NM',name:'dstr_type_nm', type: 'string'},	
				{mapping:'DEPT_NM',name:'dept_nm', type: 'string'},	
				{mapping:'DEPT_CD',name:'dept_cd', type: 'string'},	
				{mapping:'USER_NM',name:'user_nm', type: 'string'},	
				{mapping:'USER_CD',name:'user_cd', type: 'string'},	
				{mapping:'CUST_SMP_CD',name:'cust_smp_cd', type: 'string'},	
				{mapping:'MOLD_NO',name:'mold_no', type: 'string'},	
				{mapping:'RUSER_NM',name:'ruser_nm', type: 'string'}, 
				{mapping:'MUSER_NM',name:'muser_nm', type: 'string'},	
				{mapping:'MUSER_CD',name:'muser_cd', type: 'string'}, 	
				{mapping:'MDEPT_CD',name:'mdept_cd', type: 'string'},		
				{mapping:'MDEPT_NM',name:'mdept_nm', type: 'string'},			
				{mapping:'ITEM_TYPE',name:'item_type', type: 'string'},		
				{mapping:'SMP_STATUS',name:'smp_status', type: 'string'},
				{mapping:'SMP_STATUS_NM',name:'smp_status_nm', type: 'string'},
				{mapping:'PRDT_PSBLT',name:'prdt_psblt', type: 'string'},	
				{mapping:'PRDT_PSBLT_VALUE_NM',name:'prdt_psblt_value_nm', type: 'string'},	
				{mapping:'PRDT_PSBLT_NM',name:'prdt_psblt_nm', type: 'string'},	
				{mapping:'SMP_RDATE',name:'smp_rdate', type: 'date', dateFormat:'Ymd'},
				{mapping:'PRDT_RCDATE',name:'prdt_rcdate', type: 'date', dateFormat:'Ymd'},				
				{mapping:'CMPT_RDATE',name:'cmpt_rdate', type: 'date', dateFormat:'Ymd'},
				{mapping:'PRDT_RDATE',name:'prdt_rdate', type: 'date', dateFormat:'Ymd'},	
				{mapping:'PRDT_RUSER',name:'prdt_ruser', type: 'string'},	
				{mapping:'PRDT_RUSER_NM',name:'prdt_ruser_nm', type: 'string'},	
				{mapping:'PRDT_ADATE',name:'prdt_adate', type: 'date', dateFormat:'Ymd'},	
				{mapping:'PRDT_AUSER',name:'prdt_auser', type: 'string'},	
				{mapping:'PRDT_AUSER_NM',name:'prdt_auser_nm', type: 'string'},	
				{mapping:'PRDT_PDATE',name:'prdt_pdate', type: 'date', dateFormat:'Ymd'},
				{mapping:'PRDT_CDATE',name:'prdt_cdate', type: 'date', dateFormat:'Ymd'},	
				{mapping:'PRDT_CUSER',name:'prdt_cuser', type: 'string'},	
				{mapping:'PRDT_CUSER_NM',name:'prdt_cuser_nm', type: 'string'},	
				{mapping:'SHIP_PDATE',name:'ship_pdate', type: 'date', dateFormat:'Ymd'},	
				{mapping:'SHIP_PUSER',name:'ship_puser', type: 'string'},		
				{mapping:'SHIP_PUSER_NM',name:'ship_puser_nm', type: 'string'},	
				{mapping:'SMP_SUMRY',name:'smp_sumry', type: 'string'},		
				{mapping:'BASE_CRNY',name:'base_crny', type: 'string'},	
				{mapping:'EXCH_RATE',name:'exch_rate', type: 'string'},	
				{mapping:'BASE_YR',name:'base_yr', type: 'string'},
				{mapping:'SMP_RQTY',name:'smp_rqty', type: 'string'},
				{mapping:'SMP_RQTY2',name:'smp_rqty2', type: 'string'},
				{mapping:'SMP_QTY',name:'smp_qty', type: 'string'},
				{mapping:'SMP_TYPE',name:'smp_type', type: 'string'},	
				{mapping:'PRDT_CMT',name:'prdt_cmt', type: 'string'},	
				{mapping:'SMP_TYPE_NM',name:'smp_type_nm', type: 'string'},	
				{ mapping: 'FILM_FDATE', name: 'film_fdate', type: 'date', dateFormat: 'Ymd' },
                { mapping: 'FILM_CDATE', name: 'film_cdate', type: 'date', dateFormat: 'Ymd' },
                { mapping: 'TARGET_FDATE', name: 'target_fdate', type: 'date', dateFormat: 'Ymd' },
				{mapping:'FILM_RDATE',name:'film_rdate', type: 'date', dateFormat:'Ymd'}, 
				{mapping:'FILM_RUSER_NM',name:'film_ruser_nm', type: 'string'},	
				{mapping:'DROP_BTN_YN',name:'drop_btn_yn', type: 'string'},	
				{mapping:'SMP_RE_YN',name:'smp_re_yn', type: 'string'},	
				{mapping:'SMP_MY_RE_YN',name:'smp_my_re_yn', type: 'string'},	
				{ mapping: 'SMP_RT_YN', name: 'smp_rt_yn', type: 'string' },
                { mapping: 'SPEC_YN', name: 'spec_yn', type: 'string' },
				{ mapping:'SMR_CD',name:'smr_cd',  type: 'string'},				
				{ mapping: 'SMR_CHASU', name: 'smr_chasu', type: 'string' }, 
                { mapping: 'PRDT_PDATE2', name: 'prdt_pdate2', type: 'date', dateFormat: 'Ymd' },
				{ mapping: 'DELAY_COMMENT', name: 'delay_comment_cd', type: 'string' }, 
                { mapping: 'PROCESS', name: 'process_cd', type: 'string' },
                { mapping: 'DELAY_COMMENT_NM', name: 'delay_comment_nm', type: 'string' },
                { mapping: 'PROCESS_NM', name: 'process_nm', type: 'string' },
                { mapping: 'TRACKING_NUM', name: 'tracking_num', type: 'string' },
                { mapping: 'NONFREE_YN', name: 'nonfree_yn', type: 'string' }, 
                { mapping: 'PUR_OQTY', name: 'pur_oqty', type: 'string' }
            ]  
});

Ext.define('Ysn.model.sampleSpecChk', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'smr_cd', type: 'string', mapping: 'SMR_CD'    },               
        { name: 'smr_chasu', type: 'string', mapping: 'SMR_CHASU' },
        { name: 'smp_cd', type: 'string', mapping: 'SMP_CD' },
        { name: 'smp_chasu', type: 'string', mapping: 'SMP_CHASU' },
        { name: 'p_tube_overcap', type: 'string', mapping: 'P_TUBE_OVERCAP' },
        { name: 'p_tube_pump', type: 'string', mapping: 'P_TUBE_PUMP' },
        { name: 'p_tube_sleeve', type: 'string', mapping: 'P_TUBE_SLEEVE' },
        { name: 'a_tube_overcap', type: 'string', mapping: 'A_TUBE_OVERCAP' },
        { name: 'a_tube_pump', type: 'string', mapping: 'A_TUBE_PUMP' },
        { name: 'a_tube_sleeve', type: 'string', mapping: 'A_TUBE_SLEEVE' },
        { name: 'p_tube_overcap_check', type: 'string', mapping: 'P_TUBE_OVERCAP_CHECK' },
        { name: 'p_tube_pump_check', type: 'string', mapping: 'P_TUBE_PUMP_CHECK' },
        { name: 'p_tube_sleeve_check', type: 'string', mapping: 'P_TUBE_SLEEVE_CHECK' },
        { name: 'a_tube_overcap_check', type: 'string', mapping: 'A_TUBE_OVERCAP_CHECK' },
        { name: 'a_tube_pump_check', type: 'string', mapping: 'A_TUBE_PUMP_CHECK' },
        { name: 'a_tube_sleeve_check', type: 'string', mapping: 'A_TUBE_SLEEVE_CHECK' },
        { name: 'a_tube_overcap_comment', type: 'string', mapping: 'A_TUBE_OVERCAP_COMMENT' },
        { name: 'a_tube_pump_comment', type: 'string', mapping: 'A_TUBE_PUMP_COMMENT' },
        { name: 'a_tube_sleeve_comment', type: 'string', mapping: 'A_TUBE_SLEEVE_COMMENT' },
        { name: 'p_tube_overcap_comment', type: 'string', mapping: 'P_TUBE_OVERCAP_COMMENT' },
        { name: 'p_tube_pump_comment', type: 'string', mapping: 'P_TUBE_PUMP_COMMENT' },
        { name: 'p_tube_sleeve_comment', type: 'string', mapping: 'P_TUBE_SLEEVE_COMMENT' },
        { name: 'p_pump_overcap', type: 'string', mapping: 'P_PUMP_OVERCAP' },
        { name: 'p_pump_pump', type: 'string', mapping: 'P_PUMP_PUMP' },
        { name: 'p_pump_cont', type: 'string', mapping: 'P_PUMP_CONT' },
        { name: 'p_pump_support', type: 'string', mapping: 'P_PUMP_SUPPORT' },
        { name: 'a_pump_overcap', type: 'string', mapping: 'A_PUMP_OVERCAP' },
        { name: 'a_pump_pump', type: 'string', mapping: 'A_PUMP_PUMP' },
        { name: 'a_pump_cont', type: 'string', mapping: 'A_PUMP_CONT' },
        { name: 'a_pump_support', type: 'string', mapping: 'A_PUMP_SUPPORT' },
        { name: 'p_pump_overcap_check', type: 'string', mapping: 'P_PUMP_OVERCAP_CHECK' },
        { name: 'p_pump_pump_check', type: 'string', mapping: 'P_PUMP_PUMP_CHECK' },
        { name: 'p_pump_cont_check', type: 'string', mapping: 'P_PUMP_CONT_CHECK' },
        { name: 'p_pump_support_check', type: 'string', mapping: 'P_PUMP_SUPPORT_CHECK' },
        { name: 'a_pump_overcap_check', type: 'string', mapping: 'A_PUMP_OVERCAP_CHECK' },
        { name: 'a_pump_pump_check', type: 'string', mapping: 'A_PUMP_PUMP_CHECK' },
        { name: 'a_pump_cont_check', type: 'string', mapping: 'A_PUMP_CONT_CHECK' },
        { name: 'a_pump_support_check', type: 'string', mapping: 'A_PUMP_SUPPORT_CHECK' },
        { name: 'p_pump_overcap_comment', type: 'string', mapping: 'P_PUMP_OVERCAP_COMMENT' },
        { name: 'p_pump_pump_comment', type: 'string', mapping: 'P_PUMP_PUMP_COMMENT' },
        { name: 'p_pump_cont_comment', type: 'string', mapping: 'P_PUMP_CONT_COMMENT' },
        { name: 'p_pump_support_comment', type: 'string', mapping: 'P_PUMP_SUPPORT_COMMENT' },
        { name: 'a_pump_overcap_comment', type: 'string', mapping: 'A_PUMP_OVERCAP_COMMENT' },
        { name: 'a_pump_pump_comment', type: 'string', mapping: 'A_PUMP_PUMP_COMMENT' },
        { name: 'a_pump_cont_comment', type: 'string', mapping: 'A_PUMP_CONT_COMMENT' },
        { name: 'a_pump_support_comment', type: 'string', mapping: 'A_PUMP_SUPPORT_COMMENT' }
    ]
});
 
Ext.define('Ysn.model.sampleDropList', {   
            extend: 'Ext.data.Model', 
            fields: [  
			    {name:'SMP_CD',	type: 'string'},			
				{name:'SMP_CHASU', type: 'string'},	
				{name:'SMP_DRDATE', type: 'date', dateFormat:'Ymd'},	 
				{name:'ITEM_NM', type: 'string'},	
				{name:'ITEM_CD', type: 'string'},		
				{name:'CUST_NM', type: 'string'},	
				{name:'CUST_CD', type: 'string'},			
				{name:'EUSER_NM', type: 'string'},	
				{name:'EUSER_CD', type: 'string'},	
				{name:'DSTR_TYPE', type: 'string'},	
				{name:'DSTR_TYPE_NM', type: 'string'},	
				{name:'DEPT_NM', type: 'string'},	
				{name:'DEPT_CD', type: 'string'},	
				{name:'USER_NM', type: 'string'},	
				{name:'USER_CD', type: 'string'},		
				{name:'SMP_DRTYPE', type: 'string'},	
				{name:'SMP_DRTYPE_NM', type: 'string'},	
				{name:'BIZ_TYPE', type: 'string'},	
				{name:'BIZ_TYPE_NM', type: 'string'}, 
				{name:'ITEM_TYPE', type: 'string'},	
				{name:'ITEM_TYPE_NM', type: 'string'},	 	
				{name:'SMP_RDATE', type: 'date', dateFormat:'Ymd'},
				{name:'PRDT_CCDATE', type: 'date', dateFormat:'Ymd'}, 
				{name:'CMPT_RDATE', type: 'date', dateFormat:'Ymd'},
				{name:'SHIP_PDATE', type: 'date', dateFormat:'Ymd'}, 		
				{name:'BAD_AR_YN',  type: 'string'} 
            ]  
}); 
			
Ext.define('Ysn.model.sampleDropDetail', {   
            extend: 'Ext.data.Model', 
            fields: [  
			    {mapping:'SMP_CD', name:'smp_cd',	type: 'string'},			
				{mapping:'SMP_CHASU',name:'smp_chasu',	type: 'string'}, 	
				{mapping:'ITEM_NM',	name:'item_nm',	type: 'string'},	
				{mapping:'ITEM_CD',name:'item_cd',		type: 'string'},	
				{mapping:'PJT_CD',name:'pjt_cd',	type: 'string'},	
				{mapping:'PJT_NM',name:'pjt_nm',	type: 'string'},				
				{mapping:'CUST_NM',name:'cust_nm', type: 'string'},	
				{mapping:'CUST_CD',name:'cust_cd', type: 'string'},			
				{mapping:'EUSER_NM',name:'euser_nm', type: 'string'},	
				{mapping:'EUSER_CD',name:'euser_cd', type: 'string'},	
				{mapping:'BIZ_TYPE',name:'biz_type', type: 'string'},	
				{mapping:'BIZ_TYPE_NM',name:'biz_type_nm', type: 'string'},	
				{mapping:'DSTR_TYPE',name:'dstr_type', type: 'string'},	
				{mapping:'DSTR_TYPE_NM',name:'dstr_type_nm', type: 'string'},	
				{mapping:'DEPT_NM',name:'dept_nm', type: 'string'},	
				{mapping:'DEPT_CD',name:'dept_cd', type: 'string'},	
				{mapping:'USER_NM',name:'user_nm', type: 'string'},	
				{mapping:'USER_CD',name:'user_cd', type: 'string'},	
				{mapping:'CUST_SMP_CD',name:'cust_smp_cd', type: 'string'},	
				{mapping:'MOLD_NO',name:'mold_no', type: 'string'},	
				{mapping:'RUSER_NM',name:'ruser_nm', type: 'string'}, 
				{mapping:'MUSER_NM',name:'muser_nm', type: 'string'},	
				{mapping:'MUSER_CD',name:'muser_cd', type: 'string'}, 	
				{mapping:'MDEPT_CD',name:'mdept_cd', type: 'string'},		
				{mapping:'MDEPT_NM',name:'mdept_nm', type: 'string'}, 	
				{mapping:'SMP_STATUS',name:'smp_status', type: 'string'},
				{mapping:'SMP_STATUS_NM',name:'smp_status_nm', type: 'string'},
				{mapping:'PRDT_PSBLT',name:'prdt_psblt', type: 'string'},	
				{mapping:'PRDT_PSBLT_VALUE_NM',name:'prdt_psblt_value_nm', type: 'string'},	
				{mapping:'PRDT_PSBLT_NM',name:'prdt_psblt_nm', type: 'string'},	
				{mapping:'SMP_RDATE',name:'smp_rdate', type: 'date', dateFormat:'Ymd'},
				{mapping:'PRDT_RCDATE',name:'prdt_rcdate', type: 'date', dateFormat:'Ymd'},				
				{mapping:'CMPT_RDATE',name:'cmpt_rdate', type: 'date', dateFormat:'Ymd'},
				{mapping:'PRDT_RDATE',name:'prdt_rdate', type: 'date', dateFormat:'Ymd'},	
				{mapping:'PRDT_RUSER',name:'prdt_ruser', type: 'string'},	
				{mapping:'PRDT_RUSER_NM',name:'prdt_ruser_nm', type: 'string'},	
				{mapping:'PRDT_ADATE',name:'prdt_adate', type: 'date', dateFormat:'Ymd'},	
				{mapping:'PRDT_AUSER',name:'prdt_auser', type: 'string'},	
				{mapping:'PRDT_AUSER_NM',name:'prdt_auser_nm', type: 'string'},	
				{mapping:'PRDT_PDATE',name:'prdt_pdate', type: 'date', dateFormat:'Ymd'},
				{mapping:'PRDT_CDATE',name:'prdt_cdate', type: 'date', dateFormat:'Ymd'},	
				{mapping:'PRDT_CUSER',name:'prdt_cuser', type: 'string'},	
				{mapping:'PRDT_CUSER_NM',name:'prdt_cuser_nm', type: 'string'},	
				{mapping:'SHIP_PDATE',name:'ship_pdate', type: 'date', dateFormat:'Ymd'},	
				{mapping:'SHIP_PUSER',name:'ship_puser', type: 'string'},		
				{mapping:'SHIP_PUSER_NM',name:'ship_puser_nm', type: 'string'},	
				{mapping:'SMP_SUMRY',name:'smp_sumry', type: 'string'},		
				{mapping:'BASE_CRNY',name:'base_crny', type: 'string'},	
				{mapping:'EXCH_RATE',name:'exch_rate', type: 'string'},	
				{mapping:'BASE_YR',name:'base_yr', type: 'string'}, 
				{mapping:'SMP_QTY',name:'smp_qty', type: 'string'},
				{mapping:'SMP_TYPE',name:'smp_type', type: 'string'},	
				{mapping:'PRDT_CMT',name:'prdt_cmt', type: 'string'},	
				{mapping:'SMP_TYPE_NM',name:'smp_type_nm', type: 'string'},	
				{mapping:'FILM_FDATE',name:'film_fdate', type: 'date', dateFormat:'Ymd'},
				{mapping:'FILM_RDATE',name:'film_rdate', type: 'date', dateFormat:'Ymd'}, 
				{mapping:'FILM_RUSER_NM',name:'film_ruser_nm', type: 'string'},	
				{mapping:'DROP_BTN_YN',name:'drop_btn_yn', type: 'string'},	
				{mapping:'SMP_RE_YN',name:'smp_re_yn', type: 'string'},	
				{mapping:'SMP_MY_RE_YN',name:'smp_my_re_yn', type: 'string'},	
				{mapping:'SMP_RT_YN',name:'smp_rt_yn', type: 'string'},	 				
				{mapping:'SMR_CD',name:'smr_cd',  type: 'string'},				
				{mapping:'SMR_CHASU',name:'smr_chasu',  type: 'string'}	 	 
            ]  
});

Ext.define('Ysn.model.sampleDropPopup', {   
            extend: 'Ext.data.Model', 
            fields: [  
			    {mapping:'SMP_CD', name:'smp_cd',	type: 'string'},			
				{mapping:'SMP_CHASU',name:'smp_chasu',	type: 'string'}, 	
				{mapping:'SMP_STATUS',	name:'smp_status',	type: 'string'},	
				{mapping:'LOGIN_USER_NM',name:'login_user_nm',		type: 'string'},	
				{mapping:'LOGIN_DEPT_NM',name:'login_dept_nm',	type: 'string'},	
				{mapping:'DROP_DAY',name:'drop_day',	type: 'date', dateFormat:'Ymd'},				
				{mapping:'SMP_DRTYPE',name:'smp_drtype', type: 'string'},	
				{mapping:'SMP_DRDESCRIPT',name:'smp_drdescript', type: 'string'},
				{mapping:'ITEM_NM', name:'item_nm', type: 'string'},	
				{mapping:'SMP_DROP',name:'smp_drop', type: 'string'}	 
            ]  
});

Ext.define('Ysn.model.sampleMyrepairPopup', {   
            extend: 'Ext.data.Model', 
            fields: [  
			    {mapping:'SMP_CD', name:'smp_cd',	type: 'string'},			
				{mapping:'SMP_CHASU',name:'smp_chasu',	type: 'string'}, 	
				{mapping:'SMP_STATUS',	name:'smp_status',	type: 'string'},	
				{mapping:'LOGIN_USER_NM',name:'login_user_nm',		type: 'string'},	
				{mapping:'LOGIN_DEPT_NM',name:'login_dept_nm',	type: 'string'},	
				{mapping:'REPAIR_DAY',name:'repair_day',	type: 'date', dateFormat:'Ymd'},				
				{mapping:'SMP_QRTYPE',name:'smp_qrtype', type: 'string'},	
				{mapping:'SMP_QRDESCRIPT',name:'smp_qrdescript', type: 'string'},
				{mapping:'ITEM_NM', name:'item_nm', type: 'string'},				
				{mapping:'CUST_NM',name:'cust_nm', type: 'string'},		
				{mapping:'REPAIR_YN',name:'repair_yn', type: 'string'}	 
            ]  
});

Ext.define('Ysn.model.sampleRepairPopup', {   
            extend: 'Ext.data.Model', 
            fields: [  
			   {mapping:'SMP_CD', name:'smp_cd',	type: 'string'},			
				{mapping:'SMP_CHASU',name:'smp_chasu',	type: 'string'}, 	
				{mapping:'SMP_STATUS',	name:'smp_status',	type: 'string'},	
				{mapping:'LOGIN_USER_NM',name:'login_user_nm',		type: 'string'},	
				{mapping:'LOGIN_DEPT_NM',name:'login_dept_nm',	type: 'string'},	
				{mapping:'REPAIR_DAY',name:'repair_day',	type: 'date', dateFormat:'Ymd'},				
				{mapping:'SMP_CRTYPE',name:'smp_crtype', type: 'string'},	
				{mapping:'SMP_CRDESCRIPT',name:'smp_crdescript', type: 'string'},
				{mapping:'ITEM_NM', name:'item_nm', type: 'string'},					
				{mapping:'CUST_NM',name:'cust_nm', type: 'string'},	
				{mapping:'REPAIR_YN',name:'repair_yn', type: 'string'}	 
            ]  
});

Ext.define('Ysn.model.sampleRejectPopup', {   
            extend: 'Ext.data.Model', 
            fields: [  
			   {mapping:'SMP_CD', name:'smp_cd',	type: 'string'},			
				{mapping:'SMP_CHASU',name:'smp_chasu',	type: 'string'}, 	
				{mapping:'SMP_STATUS',	name:'smp_status',	type: 'string'},	
				{mapping:'LOGIN_USER_NM',name:'login_user_nm',		type: 'string'},	
				{mapping:'LOGIN_DEPT_NM',name:'login_dept_nm',	type: 'string'},	
				{mapping:'SMP_RTDATE',name:'smp_rtdate',	type: 'date', dateFormat:'Ymd'},				
				{mapping:'SMP_RTTYPE',name:'smp_rttype', type: 'string'},	
				{mapping:'SMP_RTDESCRIPT',name:'smp_rtdescript', type: 'string'},
				{mapping:'ITEM_NM', name:'item_nm', type: 'string'},					
				{mapping:'CUST_NM',name:'cust_nm', type: 'string'},	
				{mapping:'BTN_YN',name:'btn_yn', type: 'string'},	
				{mapping:'SMP_RT_YN',name:'smp_rt_yn', type: 'string'}	 
            ]  
});

Ext.define('Ysn.model.sampleSmrRejectPopup', {   
            extend: 'Ext.data.Model', 
            fields: [  
			   {mapping:'SMR_CD', name:'smr_cd',	type: 'string'},			
				{mapping:'SMR_CHASU',name:'smr_chasu',	type: 'string'}, 	
				{mapping:'SMP_STATUS',	name:'smp_status',	type: 'string'},	
				{mapping:'LOGIN_USER_NM',name:'login_user_nm',		type: 'string'},	
				{mapping:'LOGIN_DEPT_NM',name:'login_dept_nm',	type: 'string'},	
				{mapping:'SMR_RTDATE',name:'smr_rtdate',	type: 'date', dateFormat:'Ymd'},				
				{mapping:'SMR_RTTYPE',name:'smr_rttype', type: 'string'},	
				{mapping:'SMR_RTDESCRIPT',name:'smr_rtdescript', type: 'string'},
				{mapping:'ITEM_NM', name:'item_nm', type: 'string'},					
				{mapping:'EUSER_NM',name:'cust_nm', type: 'string'},	
				{mapping:'BTN_YN',name:'btn_yn', type: 'string'}	 
            ]  
});

Ext.define('Ysn.model.sampleSmrReviewPopup', {
    extend: 'Ext.data.Model',
    fields: [
       { mapping: 'SMR_CD', name: 'smr_cd', type: 'string' },
        { mapping: 'SMR_CHASU', name: 'smr_chasu', type: 'string' },
        { mapping: 'SMP_STATUS', name: 'smp_status', type: 'string' },
        { mapping: 'LOGIN_USER_NM', name: 'login_user_nm', type: 'string' },
        { mapping: 'LOGIN_DEPT_NM', name: 'login_dept_nm', type: 'string' },
        { mapping: 'SMR_RVDATE', name: 'smr_rvdate', type: 'date', dateFormat: 'Ymd' },
        { mapping: 'SMR_RVTYPE', name: 'smr_rvtype', type: 'string' },
        { mapping: 'SMR_RVDESCRIPT', name: 'smr_rvdescript', type: 'string' },
        { mapping: 'ITEM_NM', name: 'item_nm', type: 'string' },
        { mapping: 'EUSER_NM', name: 'cust_nm', type: 'string' },
        { mapping: 'BTN_YN', name: 'btn_yn', type: 'string' } 
    ]
});

Ext.define('Ysn.model.sampleSmrRepairPopup', {
    extend: 'Ext.data.Model',
    fields: [
        { mapping: 'SMR_CD', name: 'smr_cd', type: 'string' },
        { mapping: 'SMR_CHASU', name: 'smr_chasu', type: 'string' },
        { mapping: 'SMP_STATUS', name: 'smp_status', type: 'string' },
        { mapping: 'LOGIN_USER_NM', name: 'login_user_nm', type: 'string' },
        { mapping: 'LOGIN_DEPT_NM', name: 'login_dept_nm', type: 'string' },
        { mapping: 'REPAIR_DAY', name: 'repair_day', type: 'date', dateFormat: 'Ymd' },
        { mapping: 'SMR_CRTYPE', name: 'smr_crtype', type: 'string' },
        { mapping: 'SMR_CRDESCRIPT', name: 'smr_crdescript', type: 'string' },
        { mapping: 'ITEM_NM', name: 'item_nm', type: 'string' },
        { mapping: 'EUSER_NM', name: 'cust_nm', type: 'string' },
        { mapping: 'REPAIR_YN', name: 'repair_yn', type: 'string' }
    ]
});

Ext.define('Ysn.model.sampleSmrDropPopup', {
    extend: 'Ext.data.Model',
    fields: [
        { mapping: 'SMR_CD', name: 'smr_cd', type: 'string' },
        { mapping: 'SMR_CHASU', name: 'smr_chasu', type: 'string' },
        { mapping: 'SMP_STATUS', name: 'smp_status', type: 'string' },
        { mapping: 'LOGIN_USER_NM', name: 'login_user_nm', type: 'string' },
        { mapping: 'LOGIN_DEPT_NM', name: 'login_dept_nm', type: 'string' },
        { mapping: 'DROP_DAY', name: 'drop_day', type: 'date', dateFormat: 'Ymd' },
        { mapping: 'SMR_DRTYPE', name: 'smr_drtype', type: 'string' },
        { mapping: 'SMR_DRDESCRIPT', name: 'smr_drdescript', type: 'string' },
        { mapping: 'ITEM_NM', name: 'item_nm', type: 'string' },
        { mapping: 'SMR_DROP', name: 'smr_drop', type: 'string' }
    ]
});